/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Role = { 'student' : bigint } |
  { 'parent' : null };
export interface T { 'id' : bigint, 'title' : string, 'description' : string }
export interface T__1 { 'id' : bigint, 'role' : Role, 'fullName' : string }
export interface T__2 {
  'id' : bigint,
  'studentId' : bigint,
  'mastered' : boolean,
  'attempts' : bigint,
  'letter' : string,
}
export interface T__3 {
  'id' : bigint,
  'title' : string,
  'announcementType' : string,
  'body' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPhonic' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[string, string, string], undefined>,
  'createProfile' : ActorMethod<[string, Role], undefined>,
  'createQuestion' : ActorMethod<
    [string, Array<string>, string, string, bigint],
    undefined
  >,
  'createWorksheet' : ActorMethod<[string, string], undefined>,
  'getAnnouncements' : ActorMethod<[], Array<T__3>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [T__1]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getProfile' : ActorMethod<[Principal], [] | [T__1]>,
  'getStudentPhonics' : ActorMethod<[bigint], Array<T__2>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [T__1]>,
  'getWorksheets' : ActorMethod<[], Array<T>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, Role], undefined>,
  'submitTestSession' : ActorMethod<[bigint, bigint], undefined>,
  'updatePhonic' : ActorMethod<[bigint, boolean, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];