/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({ 'student' : IDL.Nat, 'parent' : IDL.Null });
export const T__3 = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'announcementType' : IDL.Text,
  'body' : IDL.Text,
});
export const T__1 = IDL.Record({
  'id' : IDL.Nat,
  'role' : Role,
  'fullName' : IDL.Text,
});
export const T__2 = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'mastered' : IDL.Bool,
  'attempts' : IDL.Nat,
  'letter' : IDL.Text,
});
export const T = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPhonic' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createProfile' : IDL.Func([IDL.Text, Role], [], []),
  'createQuestion' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createWorksheet' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(T__1)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(T__1)], ['query']),
  'getStudentPhonics' : IDL.Func([IDL.Nat], [IDL.Vec(T__2)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(T__1)], ['query']),
  'getWorksheets' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, Role], [], []),
  'submitTestSession' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updatePhonic' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({ 'student' : IDL.Nat, 'parent' : IDL.Null });
  const T__3 = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'announcementType' : IDL.Text,
    'body' : IDL.Text,
  });
  const T__1 = IDL.Record({
    'id' : IDL.Nat,
    'role' : Role,
    'fullName' : IDL.Text,
  });
  const T__2 = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'mastered' : IDL.Bool,
    'attempts' : IDL.Nat,
    'letter' : IDL.Text,
  });
  const T = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPhonic' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createProfile' : IDL.Func([IDL.Text, Role], [], []),
    'createQuestion' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createWorksheet' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(T__1)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(T__1)], ['query']),
    'getStudentPhonics' : IDL.Func([IDL.Nat], [IDL.Vec(T__2)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(T__1)], ['query']),
    'getWorksheets' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, Role], [], []),
    'submitTestSession' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updatePhonic' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };